In [1]:
import librosa
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

C:\Users\User\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
C:\Users\User\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [2]:
# Function to load in the spectrogram of each audio file
def file_loader(file_name):
    X, sample_rate = librosa.load(file_name, duration=2.97)
    ps = librosa.feature.melspectrogram(y=X, sr=sample_rate)
    return ps

In [3]:
# load in all rows all sample information from dataset
df = pd.read_csv("train/train.csv")

In [4]:
# create a unique list of all audio sound choices
catalog = df['Class'].unique().tolist()
catalog = [i for i in enumerate(catalog)]
catalog

[(0, 'siren'),
 (1, 'street_music'),
 (2, 'drilling'),
 (3, 'dog_bark'),
 (4, 'children_playing'),
 (5, 'gun_shot'),
 (6, 'engine_idling'),
 (7, 'air_conditioner'),
 (8, 'jackhammer'),
 (9, 'car_horn')]

[(0, 'siren'),
 (1, 'street_music'),
 (2, 'drilling'),
 (3, 'dog_bark'),
 (4, 'children_playing'),
 (5, 'gun_shot'),
 (6, 'engine_idling'),
 (7, 'air_conditioner'),
 (8, 'jackhammer'),
 (9, 'car_horn')]

In [8]:
# create an array for "Y"
labels = np.empty(0)
# create list of arrays for "X"
transformed_samples = []
# pull through the data and load each file
for i in range(df.shape[0]):
    number = df.iloc[i,0]
    label = df.iloc[i,1]
    filename = f'{number}.wav'
    lbl = f'{label}'
    try:
        ps = file_loader(f'train/train/{filename}')
        if ps.shape != (128, 128): continue
    except:
        print(f"File {filename} didn't work")
        continue
    transformed_samples.append(np.reshape(ps, -1))
    #load in the labels into Y by number
    if label == catalog[0][1]:
        labels = np.append(labels, catalog[0][0])
    elif label == catalog[1][1]:
        labels = np.append(labels, catalog[1][0])
    elif label == catalog[2][1]:
        labels = np.append(labels, catalog[2][0])
    elif label == catalog[3][1]:
        labels = np.append(labels, catalog[3][0])
    elif label == catalog[4][1]:
        labels = np.append(labels, catalog[4][0])
    elif label == catalog[5][1]:
        labels = np.append(labels, catalog[5][0])
    elif label == catalog[6][1]:
        labels = np.append(labels, catalog[6][0])
    elif label == catalog[7][1]:
        labels = np.append(labels, catalog[7][0])
    elif label == catalog[8][1]:
        labels = np.append(labels, catalog[8][0])
    elif label == catalog[9][1]:
        labels = np.append(labels, catalog[9][0])

In [9]:
# put transformed_samples into dataframe
df_1 = pd.DataFrame(transformed_samples)
df_1.head()

,0,1,2,3,4,5,6,7,8,9,...,16374,16375,16376,16377,16378,16379,16380,16381,16382,16383
0,9.912633,12.610701,9.300829,3.297573,4.655068,5.044219,1.048530,1.559219,1.782135,8.640504,...,4.685921e-06,7.909435e-06,9.165550e-06,6.099369e-06,6.530995e-06,5.510310e-06,5.303133e-06,7.210522e-06,5.260210e-06,0.000420
1,2.661400,4.117083,1.679421,1.527544,1.595737,2.088292,6.244799,2.845641,0.872873,0.603950,...,9.428515e-05,4.775995e-05,4.399524e-05,1.374228e-05,8.436620e-06,7.757358e-06,1.799225e-05,1.284928e-04,2.856303e-04,0.007425
2,0.005557,0.004293,0.002716,0.002533,0.006898,0.006982,0.005634,0.007432,0.014744,0.015015,...,2.457749e-03,2.147882e-03,2.373022e-03,2.072116e-03,2.920827e-03,2.892467e-03,2.193557e-03,3.515167e-03,7.447198e-03,0.010343
3,0.353371,0.096338,0.003695,0.004806,0.004052,0.013310,0.013695,0.020970,0.015848,0.021949,...,1.214701e-09,2.546348e-10,7.933098e-11,2.247661e-10,4.596068e-10,2.116015e-10,7.314918e-11,1.394108e-10,4.291821e-08,0.000476
4,166.046129,102.582782,34.110469,51.670868,44.564469,57.289162,119.480505,65.250017,64.334011,80.964602,...,3.375942e-07,2.726756e-07,4.011556e-07,4.404903e-07,4.052210e-07,5.836523e-07,5.716864e-07,4.060787e-07,5.430899e-07,0.000350

,0,1,2,3,4,5,6,7,8,9,...,16374,16375,16376,16377,16378,16379,16380,16381,16382,16383
0,9.912633,12.610701,9.300829,3.297573,4.655068,5.044219,1.048530,1.559219,1.782135,8.640504,...,4.685921e-06,7.909435e-06,9.165550e-06,6.099369e-06,6.530995e-06,5.510310e-06,5.303133e-06,7.210522e-06,5.260210e-06,0.000420
1,2.661400,4.117083,1.679421,1.527544,1.595737,2.088292,6.244799,2.845641,0.872873,0.603950,...,9.428515e-05,4.775995e-05,4.399524e-05,1.374228e-05,8.436620e-06,7.757358e-06,1.799225e-05,1.284928e-04,2.856303e-04,0.007425
2,0.005557,0.004293,0.002716,0.002533,0.006898,0.006982,0.005634,0.007432,0.014744,0.015015,...,2.457749e-03,2.147882e-03,2.373022e-03,2.072116e-03,2.920827e-03,2.892467e-03,2.193557e-03,3.515167e-03,7.447198e-03,0.010343
3,0.353371,0.096338,0.003695,0.004806,0.004052,0.013310,0.013695,0.020970,0.015848,0.021949,...,1.214701e-09,2.546348e-10,7.933098e-11,2.247661e-10,4.596068e-10,2.116015e-10,7.314918e-11,1.394108e-10,4.291821e-08,0.000476
4,166.046129,102.582782,34.110469,51.670868,44.564469,57.289162,119.480505,65.250017,64.334011,80.964602,...,3.375942e-07,2.726756e-07,4.011556e-07,4.404903e-07,4.052210e-07,5.836523e-07,5.716864e-07,4.060787e-07,5.430899e-07,0.000350

In [10]:
# add the Labels into the dataframe
df_1["Y"] = labels
df_1.head()

,0,1,2,3,4,5,6,7,8,9,...,16375,16376,16377,16378,16379,16380,16381,16382,16383,Y
0,9.912633,12.610701,9.300829,3.297573,4.655068,5.044219,1.048530,1.559219,1.782135,8.640504,...,7.909435e-06,9.165550e-06,6.099369e-06,6.530995e-06,5.510310e-06,5.303133e-06,7.210522e-06,5.260210e-06,0.000420,0.0
1,2.661400,4.117083,1.679421,1.527544,1.595737,2.088292,6.244799,2.845641,0.872873,0.603950,...,4.775995e-05,4.399524e-05,1.374228e-05,8.436620e-06,7.757358e-06,1.799225e-05,1.284928e-04,2.856303e-04,0.007425,1.0
2,0.005557,0.004293,0.002716,0.002533,0.006898,0.006982,0.005634,0.007432,0.014744,0.015015,...,2.147882e-03,2.373022e-03,2.072116e-03,2.920827e-03,2.892467e-03,2.193557e-03,3.515167e-03,7.447198e-03,0.010343,2.0
3,0.353371,0.096338,0.003695,0.004806,0.004052,0.013310,0.013695,0.020970,0.015848,0.021949,...,2.546348e-10,7.933098e-11,2.247661e-10,4.596068e-10,2.116015e-10,7.314918e-11,1.394108e-10,4.291821e-08,0.000476,0.0
4,166.046129,102.582782,34.110469,51.670868,44.564469,57.289162,119.480505,65.250017,64.334011,80.964602,...,2.726756e-07,4.011556e-07,4.404903e-07,4.052210e-07,5.836523e-07,5.716864e-07,4.060787e-07,5.430899e-07,0.000350,3.0

,0,1,2,3,4,5,6,7,8,9,...,16375,16376,16377,16378,16379,16380,16381,16382,16383,Y
0,9.912633,12.610701,9.300829,3.297573,4.655068,5.044219,1.048530,1.559219,1.782135,8.640504,...,7.909435e-06,9.165550e-06,6.099369e-06,6.530995e-06,5.510310e-06,5.303133e-06,7.210522e-06,5.260210e-06,0.000420,0.0
1,2.661400,4.117083,1.679421,1.527544,1.595737,2.088292,6.244799,2.845641,0.872873,0.603950,...,4.775995e-05,4.399524e-05,1.374228e-05,8.436620e-06,7.757358e-06,1.799225e-05,1.284928e-04,2.856303e-04,0.007425,1.0
2,0.005557,0.004293,0.002716,0.002533,0.006898,0.006982,0.005634,0.007432,0.014744,0.015015,...,2.147882e-03,2.373022e-03,2.072116e-03,2.920827e-03,2.892467e-03,2.193557e-03,3.515167e-03,7.447198e-03,0.010343,2.0
3,0.353371,0.096338,0.003695,0.004806,0.004052,0.013310,0.013695,0.020970,0.015848,0.021949,...,2.546348e-10,7.933098e-11,2.247661e-10,4.596068e-10,2.116015e-10,7.314918e-11,1.394108e-10,4.291821e-08,0.000476,0.0
4,166.046129,102.582782,34.110469,51.670868,44.564469,57.289162,119.480505,65.250017,64.334011,80.964602,...,2.726756e-07,4.011556e-07,4.404903e-07,4.052210e-07,5.836523e-07,5.716864e-07,4.060787e-07,5.430899e-07,0.000350,3.0

In [11]:
# Split the data

X_train, X_test, y_train, y_test = train_test_split(df_1.drop("Y", axis=1), df_1["Y"], random_state=1)

In [12]:
# Always scale your data

scaler = MinMaxScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
# set up random forest
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.7722174288179465

0.7722174288179465

In [14]:
# gridsearch crossvalidation (cv parameter)
#

In [17]:
# drop in single example to see prediction
rf.predict(df_1.drop("Y", axis=1).iloc[2].values.reshape(1,-1))

array([2.])

array([2.])

In [18]:
df_1["Y"].iloc[2]

2.0

2.0